# services:
#   postgres:
#     image: postgres:17
#     ports:
#       - 5433:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: shopping
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data

services:
  postgres:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping
    volumes:
      - ./postgres_data:/var/lib/postgresql/data