# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - air
    silent: false
  db:up:
    cmds:
      - docker compose up

  db:migrate:new:
    cmds:
      - migrate create -ext sql -dir ./database/migrations -seq {{.name}}
  db:migrate:up:
    cmds:
      - migrate -database "postgresql://postgres:postgres@localhost:5433/shopping?sslmode=disable" -path ./database/migrations up 1
  db:migrate:down:
    cmds:
      - migrate -database "postgresql://postgres:postgres@localhost:5433/shopping?sslmode=disable" -path ./database/migrations down 1
  db:migrate:force:
    cmds:
      - migrate -database "postgresql://postgres:postgres@localhost:5433/shopping?sslmode=disable" -path ./database/migrations force {{.version}}
  sqlc:
    cmds:
      - go tool sqlc generate
  deploy:production:
    cmds:
      - gcloud run deploy book-shopping-api --source .
