// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ShoppingList struct {
	ID        pgtype.UUID
	Name      string
	Items     []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Role      string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
