// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_list.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const shoppingListPartialUpdate = `-- name: ShoppingListPartialUpdate :one
UPDATE shopping_lists
SET name = COALESCE($2, name),
    items = COALESCE($3, items)
WHERE id = $1
RETURNING id, name, items, created_at, updated_at
`

type ShoppingListPartialUpdateParams struct {
	ID    pgtype.UUID
	Name  pgtype.Text
	Items []string
}

func (q *Queries) ShoppingListPartialUpdate(ctx context.Context, arg ShoppingListPartialUpdateParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, shoppingListPartialUpdate, arg.ID, arg.Name, arg.Items)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
