basePath: /v1
host: localhost:8080
info:
  contact: {}
  description: 'Send the jwt auth token in the Authorization token like `Authorization:
    Bearer <token>`'
  title: Shopping List API
  version: "0.1"
paths:
  /lists:
    get:
      consumes:
      - application/json
      description: Retrieve all shopping lists from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of shopping lists" example:[{"id":"123e4567-e89b-12d3-a456-426614174000","name":"Grocery
            List","items":["milk","bread","eggs"],"created_at":"2023-01-01T00:00:00Z","updated_at":"2023-01-01T00:00:00Z"}]
          schema:
            items:
              type: object
            type: array
        "401":
          description: Unauthorized - Invalid or missing token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - AuthToken: []
      summary: Get all shopping lists
      tags:
      - shopping-lists
swagger: "2.0"
